In [16]:
import numpy as np


In [17]:
np.array([[1,2,3],[4,5,6],[7,8,9]])


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
data = np.array([[0.987,0.45,0.123],[12.45,56.1,0.087]])
data

array([[ 0.987,  0.45 ,  0.123],
       [12.45 , 56.1  ,  0.087]])

In [19]:
data.dtype


dtype('float64')

In [20]:
data1 = [6,7.5,8,0,1] 
#A list is converted into an array
#Since data is mixed, it is made uniform, i.e all  is made float
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [21]:
data2 = [[1,2,3,4],[5,6,7,8]]
#A nested list of equal-length lists will be converted into a multidimensional array
arr2 = np.array(data2)
arr2


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
arr2.shape #No. of rows and how many items in each row

(2, 4)

In [23]:
arr2.ndim #It tells the dimensions of the array

2

In [24]:
np.zeros(10) #1D array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((3,3)) #3X3 dimensional array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.zeros((5,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
np.ones((3,3)) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.empty((4,5)) #Gives us garbage Values

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.06810404e-306, 1.89146896e-307],
       [7.56571288e-307, 3.11525958e-307, 1.24610723e-306,
        1.37962320e-306, 1.29060871e-306],
       [2.22518251e-306, 1.33511969e-306, 1.78022342e-306,
        1.05700345e-307, 1.11261027e-306],
       [1.11261502e-306, 1.42410839e-306, 7.56597770e-307,
        6.23059726e-307, 1.42419530e-306]])

In [29]:
np.arange(15) #1D array of values form 0 to 14

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
np.zeros((3,4,5)) # 3 matrices of 4x5 dimesnsional matrix

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [31]:
np.zeros((3,4,5,6)) # we get (3x4=12) matrices of dimension 5x6

array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
        

In [32]:
sample = np.zeros((3,4,5,6,7))
sample
#We get (3x4x5=60) matrices of dimension 6x7 and so on.

array([[[[[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

        

In [33]:
sample.shape

(3, 4, 5, 6, 7)

In [34]:
sample.ndim

5

In [35]:
np.eye(4) #identity matrix with a scalar input

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [38]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [39]:
arr+arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [40]:
arr*8.9

array([[ 8.9, 17.8, 26.7],
       [35.6, 44.5, 53.4]])

In [41]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [42]:
arr+56


array([[57, 58, 59],
       [60, 61, 62]])

In [43]:
arr = np.arange(10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr[5]


5

In [45]:
arr[5:8]


array([5, 6, 7])

In [46]:
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [47]:
arr_slice=arr[5:8]
arr_slice[1]=12345
arr


array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [48]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
#Each of the above elements caan be accessed using thw following
#arr2d[0,0],arr2d[0,1],arr2d[0,3],arr2d[1,0],arr2d[1,1],arr2d[1,2], arr2d[2,0],arr2d[2,1],arr2d[2,2]
arr2d[1,2]

6

In [50]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #This is a 2x2x3 array
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [51]:
arr3d[0]


array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
old_values = arr3d[0].copy()
arr3d[0]=42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [53]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
arr3d[1,0]
#it gives values of all the indices that start with (1,0)

#array([[[ 1,  2,  3], (0,0)
 #       [ 4,  5,  6]], (0,1)
#
 #      [[ 7,  8,  9], (1,0)
  #      [10, 11, 12]]]) (1,1)

#And then further the indices are divided.




array([7, 8, 9])

In [55]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [56]:
arr[1:6]

array([ 1,  2,  3,  4, 12])

In [57]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
arr2d[:2,1:] #This is a way to slice up the matrix



array([[2, 3],
       [5, 6]])

In [60]:
arr2d[:,:1]


array([[1],
       [4],
       [7]])

In [61]:
#if the sliced portion of he matrix is assigned a value then that applies to the entire matrix

arr2d[:2,1:]=0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [62]:
sample = np.array([[1,2,3],[4,5,6],[7,8,9]])
sample

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
sample[:2,1:]


array([[2, 3],
       [5, 6]])

In [64]:
sample[2]
sample[2,:]
sample[2:,:]

#All the above three give the same result

array([[7, 8, 9]])

In [65]:
sample[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [66]:
sample[1,:2]
sample[1:2,:2]

#The above two give the same output, so it is import to know the different ways of slicing up a matrix


array([[4, 5]])

In [67]:

data = np.random.randn(7,4)
data


array([[ 0.53718012, -0.7412039 , -1.03681474,  1.07649915],
       [ 0.50735655, -0.13083109,  1.79508158,  0.52590649],
       [ 0.06019301,  0.90176296, -0.16471609,  0.82349709],
       [-1.53553588, -0.81365107, -0.22621677, -0.76041203],
       [ 0.5001969 , -1.49768727, -0.34513417, -1.23321753],
       [ 0.41813668, -0.63032055, -0.23628018,  0.57025984],
       [-0.36906087,  0.12706441,  2.92181419,  0.24772873]])

In [68]:
data[data<0]=0
data

array([[0.53718012, 0.        , 0.        , 1.07649915],
       [0.50735655, 0.        , 1.79508158, 0.52590649],
       [0.06019301, 0.90176296, 0.        , 0.82349709],
       [0.        , 0.        , 0.        , 0.        ],
       [0.5001969 , 0.        , 0.        , 0.        ],
       [0.41813668, 0.        , 0.        , 0.57025984],
       [0.        , 0.12706441, 2.92181419, 0.24772873]])

In [84]:
arr = np.empty((8,4))
arr

array([[1.23370762e-311, 1.06224114e-321, 0.00000000e+000,
        0.00000000e+000],
       [1.89146896e-307, 5.02034658e+175, 9.90033547e+164,
        5.21733668e-037],
       [9.15716581e-071, 5.98847150e+174, 1.58669330e-076,
        7.75582538e-144],
       [3.59751658e+252, 1.46901661e+179, 8.37404147e+242,
        2.59027926e-144],
       [3.80985069e+180, 1.14428494e+243, 2.59027907e-144,
        7.79952704e-143],
       [1.27882729e+161, 2.14394224e+160, 4.30144681e+174,
        3.93208607e-061],
       [2.59027907e-144, 2.59903818e-144, 5.27365184e-091,
        3.06309741e-057],
       [3.69534359e-057, 1.11475752e+261, 1.16318408e-028,
        2.59297589e-306]])

In [85]:
arr[[4,3,0,6]]


array([[3.80985069e+180, 1.14428494e+243, 2.59027907e-144,
        7.79952704e-143],
       [3.59751658e+252, 1.46901661e+179, 8.37404147e+242,
        2.59027926e-144],
       [1.23370762e-311, 1.06224114e-321, 0.00000000e+000,
        0.00000000e+000],
       [2.59027907e-144, 2.59903818e-144, 5.27365184e-091,
        3.06309741e-057]])

In [86]:
arr

array([[1.23370762e-311, 1.06224114e-321, 0.00000000e+000,
        0.00000000e+000],
       [1.89146896e-307, 5.02034658e+175, 9.90033547e+164,
        5.21733668e-037],
       [9.15716581e-071, 5.98847150e+174, 1.58669330e-076,
        7.75582538e-144],
       [3.59751658e+252, 1.46901661e+179, 8.37404147e+242,
        2.59027926e-144],
       [3.80985069e+180, 1.14428494e+243, 2.59027907e-144,
        7.79952704e-143],
       [1.27882729e+161, 2.14394224e+160, 4.30144681e+174,
        3.93208607e-061],
       [2.59027907e-144, 2.59903818e-144, 5.27365184e-091,
        3.06309741e-057],
       [3.69534359e-057, 1.11475752e+261, 1.16318408e-028,
        2.59297589e-306]])

In [93]:
for i in range(8):
    arr[i]=i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [94]:
arr[[4,3,0,6]]


array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [95]:
arr[[-3,-5,-7]]


array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [96]:
#now what to do when we have a data but have to arrange it in the form of an array of our choice
np.arange(32)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [97]:
#So we can arrange this data in the form of a 4x8 or 8x4 or 16x2 or 2x16 matrix

arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [99]:
matrix = np.arange(32).reshape((2,16))
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [100]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [101]:
arr[[1,5,7,2],[0,3,1,2]]
#OUTPUT - array([ 4, 23, 29, 10]) // [(1,0),(5,3),(7,1),(2,2)] Outputs are in the form of particular matrices whose index combination is given as follows


array([ 4, 23, 29, 10])